#!/usr/bin/env bash
#Terminating SSL on HAproxy

global
    maxconn 4096
    log /dev/log local0
    log /dev/log local1 notice

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend www-https
    bind *:443 ssl crt /etc/letsencrypt/live/www.hlbc69nry.tech/fullchain.pem
    reqadd X-Forwarded-Proto:\ https
    default_backend www-backend

backend www-backend
    server web-server 127.0.0.1:80
