#!/usr/bin/env bash
#a Bash script that transfers a file from our client to a server

if [ "$#" -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  	file_path="$1"
	ip_address="$2"
	username="$3"
	ssh_path="$4"

	scp -o StrickHostKeyChecking=no -i "$ssh_path" "$file_path" "$username"@"$ip_address":~/
fi
