#!/usr/bin/env bash
#a Bash script that configures a new Ubuntu machine

apt-get update

#to install ngix
apt-get -y install nginx

#the html page
echo "Hello World!" > /var/www/html/index.html

#redirection page
echo "<html><head><meta hhtp-equiv='refresh' content='0;url=/new-page'></head>
</html>" > /var/www/html/redirect_me/index.html
#nginx listening to port 80
echo "server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;
	index index.html

	server_name_;

	location / {
		try_files \$uri \$uri/ =404;
	}

	location /redirect_me {
		return 301 /new-page;
	}
	
	location = /index.html {
        try_files \$uri =404;
    }
}" > /etc/nginx/sites-available/default

service nginx restart
