#!/usr/bin/env bash
#Installs and configure HAproxy on your lb-01 server

sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy
sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup

cat <<EOL | sudo tee /etc/haproxy/haproxy.cfg
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http_front
    bind *:80
    stats uri /haproxy?stats

    acl host_web_01 hdr(host) -i [315208]-web-01
    acl host_web_02 hdr(host) -i [315208]-web-02

    use_backend web_servers if host_web_01
    use_backend web_servers if host_web_02

backend web_servers
    balance roundrobin
    server web-01 [315208]-web-01:80 check
    server web-02 [315208]-web-02:80 check
EOL

# Restart HAProxy
sudo systemctl restart haproxy

# Enable HAProxy
sudo systemctl enable haproxy
