#!/usr/bin/env bash
#Debugging the web stack

#removing the default Nginx configuration file
rm /etc/nginx/sites-enabled/default
#configure nginx to listen on port 80
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
#restart nginx
service nginx restart
