#!/usr/bin/env bash
#a bash script that changes the user from root to nginx
sed -i 's/user\s*nginx;/user nginx;/g' /etc/nginx/nginx.conf
chown -R nginx:nginx /var/www/html /var/log/nginx /var/lib/nginx
sed -i 's/listen\s*80;/listen 8080;/g' /etc/nginx/sites-available/default
service nginx restart
pgrep -f 'ngin[x]'
